name: my_chat_gpt
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  equatable: ^2.0.5
  logger: ^1.3.0
  http: ^0.13.5
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  shared_preferences: ^2.0.18
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: "^0.13.0"

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/images/ic_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ic_app.png"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
