name: my_chat_gpt
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 2.1.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HELPER
  equatable: ^2.0.5
  logger: ^2.0.2+1
  http: ^1.1.2
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  animated_text_kit: ^4.2.2

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/ic_app_ios.png"
  remove_alpha_ios: true
  image_path: "assets/images/ic_app.png"
  adaptive_icon_background: "#926BF7"
  adaptive_icon_foreground: "assets/images/ic_app.png"


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
